packages:
    - name: core
      environment:
        ADMIN_USERNAME: "${ADMIN_USERNAME}"
        ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
      functions:
        - name: login_json
          binary: true
          main: ""
          runtime: go:default
          web: true
        - name: login_get
          binary: true
          main: ""
          runtime: go:default
          web: true
