parameters: {}
environment: {}
packages:
    - name: core
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: login
          binary: false
          main: ""
          runtime: go:default
          web: true
          parameters: {}
          environment: {}
          annotations: {}
          limits: {}
