packages:
    - name: core
      environment:
        SECRET_KEY: "${SECRET_KEY}"
        MONGO_CONNECTION_STRING: "${MONGO_CONNECTION_STRING}"
      functions:
        - name: login
          binary: true
          main: ""
          runtime: python:3.9
          web: true
        - name: save
          binary: true
          main: ""
          runtime: python:3.9
          web: true
