alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: agajdosi/diplomantky3
  name: diplomantky-functions
  routes:
  - path: /fce
  source_dir: /
name: diplomantky-app
region: fra

static_sites:
- build_command: hugo --destination build
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: agajdosi/diplomantky3
  name: diplomantky-static
  source_dir: web
  routes:
  - path: /
