alerts:
- rule: DEPLOYMENT_FAILED
functions:
- git:
    branch: master
    repo_clone_url: https://github.com/digitalocean/sample-functions-golang-helloworld.git
  name: sample-functions-golang-hellowor
  routes:
  - path: /sample-functions-golang-hellowor
  source_dir: /
name: DIPLOMANTKY-APP
region: fra
static_sites:
- environment_slug: html
  github:
    branch: main
    deploy_on_push: true
    repo: agajdosi/diplomantky
  name: diplomantky3
  routes:
  - path: /
  source_dir: /
