baseURL : https://diplomantky.cz
locale : cz
title : Diplomantky.cz
publishDir : ./build
DefaultContentLanguage: cz
languages:
  cz:
    label: Česky
    weight: 1
  en:
    label: English
    weight: 2
